export const dummyApplications = [
    {
        id: 1,
        positionName: 'Frontend Developer',
        companyName: 'Tech Corp',
        city: { name: 'Berlin' },
        country: { name: 'Germany' },
        workType: 'On-site',
        salaryRange: { minSalary: '50,000', maxSalary: '70,000', frequency: 'per year' },
        skills: ['JavaScript', 'Vue.js', 'CSS', 'HTML'],
        jobDescription: 'Developing user-facing features using Vue.js.',
        requirements: 'At least 3 years of experience with front-end technologies.',
    },
    {
        id: 2,
        positionName: 'Backend Developer',
        companyName: 'Innovate Ltd.',
        city: { name: 'Munich' },
        country: { name: 'Germany' },
        workType: 'Remote',
        salaryRange: { minSalary: '60,000', maxSalary: '80,000', frequency: 'per year' },
        skills: ['Node.js', 'Express', 'MongoDB'],
        jobDescription: 'Building scalable backend services and APIs.',
        requirements: 'Strong experience with Node.js and MongoDB.',
    },
    {
        id: 3,
        positionName: 'Data Scientist',
        companyName: 'Data Insights',
        city: { name: 'Hamburg' },
        country: { name: 'Germany' },
        workType: 'Hybrid',
        salaryRange: { minSalary: '40,000', maxSalary: '60,000', frequency: 'per year' },
        skills: ['Python', 'Machine Learning', 'Data Analysis'],
        jobDescription: 'Analyzing data and building predictive models.',
        requirements: 'Proficiency in Python and data analysis tools.',
    },
    {
        id: 4,
        positionName: 'Product Manager',
        companyName: 'Creatives Inc.',
        city: { name: 'Düsseldorf' },
        country: { name: 'Germany' },
        workType: 'On-site',
        salaryRange: { minSalary: '70,000', maxSalary: '90,000', frequency: 'per year' },
        skills: ['Product Management', 'Agile', 'Scrum'],
        jobDescription: 'Managing product lifecycle and coordinating with teams.',
        requirements: 'Experience in product management and agile methodologies.',
    },
    {
        id: 5,
        positionName: 'UX Designer',
        companyName: 'Design Studio',
        city: { name: 'Cologne' },
        country: { name: 'Germany' },
        workType: 'Remote',
        salaryRange: { minSalary: '50,000', maxSalary: '70,000', frequency: 'per year' },
        skills: ['UX Design', 'Wireframing', 'Prototyping'],
        jobDescription: 'Designing user experiences and creating wireframes.',
        requirements: 'Experience in UX design and prototyping tools.',
    },
    {
        id: 6,
        positionName: 'DevOps Engineer',
        companyName: 'Cloud Masters',
        city: { name: 'Frankfurt' },
        country: { name: 'Germany' },
        workType: 'On-site',
        salaryRange: { minSalary: '80,000', maxSalary: '100,000', frequency: 'per year' },
        skills: ['AWS', 'Docker', 'Kubernetes'],
        jobDescription: 'Managing cloud infrastructure and CI/CD pipelines.',
        requirements: 'Strong knowledge of cloud services and container orchestration.',
    },
    {
        id: 7,
        positionName: 'Mobile Developer',
        companyName: 'App Innovators',
        city: { name: 'Stuttgart' },
        country: { name: 'Germany' },
        workType: 'Remote',
        salaryRange: { minSalary: '60,000', maxSalary: '80,000', frequency: 'per year' },
        skills: ['Flutter', 'React Native', 'iOS', 'Android'],
        jobDescription: 'Developing cross-platform mobile applications.',
        requirements: 'Experience in mobile app development using Flutter or React Native.',
    },
    {
        id: 8,
        positionName: 'QA Engineer',
        companyName: 'Quality Labs',
        city: { name: 'Berlin' },
        country: { name: 'Germany' },
        workType: 'Hybrid',
        salaryRange: { minSalary: '40,000', maxSalary: '60,000', frequency: 'per year' },
        skills: ['Automated Testing', 'Selenium', 'Cypress'],
        jobDescription: 'Creating and executing test plans and scripts.',
        requirements: 'Experience in automated testing frameworks.',
    },
    {
        id: 9,
        positionName: 'System Administrator',
        companyName: 'IT Services',
        city: { name: 'Leipzig' },
        country: { name: 'Germany' },
        workType: 'On-site',
        salaryRange: { minSalary: '50,000', maxSalary: '70,000', frequency: 'per year' },
        skills: ['Linux', 'Networking', 'System Monitoring'],
        jobDescription: 'Managing and monitoring server infrastructure.',
        requirements: 'Experience with Linux systems and networking protocols.',
    },
];
